services:
  - type: web
    name: murojaat-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: API_TOKEN
        sync: false
